---

- name: Check slurm hostlist
  hosts: testohpc_login
  tasks:
  - name: Get slurm partition info
    command: sinfo --noheader --format="%P,%a,%l,%D,%t,%N" # using --format ensures we control whitespace
    register: sinfo
  - name:
    assert:                        # PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
      that: "sinfo.stdout_lines == ['compute*,up,60-00:00:00,2,idle,testohpc-compute-[0-1]']"
      fail_msg: "FAILED - actual value: {{ sinfo.stdout_lines }}"

- name: Run limited job and check limits
  hosts: testohpc-compute-0
  tasks:
  - name: Assert expected SelectTypeParameters
    ansible.builtin.assert:
      that: ansible_local.slurm.SelectTypeParameters in ('CR_CORE', 'CR_CORE_MEMORY')
  - ansible.builtin.shell: >
      printf '#!bin/bash\nsleep 500' | sbatch --cpus-per-task=1 --ntasks=1 --mem=200m --nodelist=testohpc-compute-0
  - name: Get cpuset cgroup limit
    shell: cat /sys/fs/cgroup/system.slice/testohpc-compute-0_slurmstepd.scope/job_*/cpuset.cpus
    register: job_cpuset
  - name: Assert cpuset cgroup presence
    assert:
      that: "job_cpuset.stdout_lines[0] in ('0', '0-1')"  # depending on the VM's state
      fail_msg: "FAILED - actual value: {{ job_cpuset.stdout_lines }}"
  - name: Check memory limit
    when: ansible_local.slurm.SelectTypeParameters == 'CR_CORE_MEMORY'
    block:
      - name: Get memory cgroup limit
        shell: cat /sys/fs/cgroup/system.slice/testohpc-compute-0_slurmstepd.scope/job_*/memory.max
        register: job_memory
      - name: Assert memory cgroup limit
        assert:
          that: "job_memory.stdout_lines == ['209715200']"
          fail_msg: "FAILED - actual value: {{ job_memory.stdout_lines }}"
