---
- name: Converge
  hosts: all
  vars:
    openhpc_enable:
      control: "{{ inventory_hostname in groups['testohpc_login'] }}"
      batch: "{{ inventory_hostname in groups['testohpc_compute'] }}"
      runtime: true
    openhpc_slurm_control_host: "{{ groups['testohpc_login'] | first }}"
    openhpc_slurm_partitions:
      - name: "compute"
        extra_nodes:
          # Need to specify IPs for the non-existent State=DOWN nodes, because otherwise even in this state slurmctld will exclude a node with no lookup information from the config.
          # We use invalid IPs here (i.e. starting 0.) to flag the fact the nodes shouldn't exist.
          # Note this has to be done via slurm config rather than /etc/hosts due to Docker limitations on modifying the latter.
          - NodeName: fake-x,fake-y
            NodeAddr: 0.42.42.0,0.42.42.1
            State: DOWN
            CPUs: 1
          - NodeName: fake-2cpu-[3,7-9]
            NodeAddr: 0.42.42.3,0.42.42.7,0.42.42.8,0.42.42.9
            State: DOWN
            CPUs: 2
    openhpc_cluster_name: testohpc
    openhpc_slurm_configless: true
  tasks:
    - name: "Include ansible-role-openhpc"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
