---
name: single partition, group is partition
driver:
  name: docker
platforms:
  - name: testohpc-login-0
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_login
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: net1
  - name: testohpc-compute-0
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
      - testohpc_compute_orig
      - testohpc_compute_new
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: net1
  - name: testohpc-compute-1
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
      - testohpc_compute_orig
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: net1
provisioner:
  name: ansible
verifier:
  name: ansible
