- name: Enable batch on login-only nodes
  # TODO: why can't we remove this by just setting openhpc_enable.batch: true for appliance login nodes??
  set_fact:
    openhpc_enable: "{{ openhpc_enable | combine({'batch': true}) }}"
  when:
    - openhpc_login_only_nodes in group_names
