- name: Check if slurm database has been initialised
  # DB is initialised on the first slurmdbd startup (without -u option).
  # If it is not initialised, `slurmdbd -u` errors with something like
  # > Slurm Database is somehow higher than expected '4294967294' but I only
  # > know as high as '16'. Conversion needed.
  community.mysql.mysql_query:
    login_db: "{{ openhpc_slurmdbd_mysql_database }}"
    login_user: "{{ openhpc_slurmdbd_mysql_username }}"
    login_password: "{{ openhpc_slurmdbd_mysql_password }}"
    #login_host: 
    query: SHOW TABLES
  register: _openhpc_slurmdb_tables

- name: Check if slurm database requires an upgrade
  ansible.builtin.command: slurmdbd -u
  register: _openhpc_slurmdbd_check
  changed_when: false
  failed_when: >-
    _openhpc_slurmdbd_check.rc > 1 or
    'Slurm Database is somehow higher than expected' in _openhpc_slurmdbd_check.stdout
  # from https://github.com/SchedMD/slurm/blob/master/src/plugins/accounting_storage/mysql/as_mysql_convert.c
  when: _openhpc_slurmdb_tables.query_result != [[]] # i.e. when db is initialised

- name: Set fact for slurm database upgrade
  # If -u option doesn't exist it can't be a major upgrade due to existing
  # appliance version
  # Otherwise from manpage, rc 0 = no conversion, 1 = conversion required
  # Default skips upgrade steps if slurmdbd is running or db not initialised
  set_fact:
    _openhpc_slurmdb_upgrade: >-
      {{ false
          if (
            ( _openhpc_slurmdbd_check.rc | default(0) )
            or
            ( "'Usage: slurmdbd' in _openhpc_slurmdbd_check.stderr" )
          ) else
          true
      }}

- name: Ensure Slurm database service stopped
  ansible.builtin.systemd:
    name: "{{ openhpc_slurm_accounting_storage_service }}"
    state: stopped
  register: _openhpc_slurmdb_state
  when: _openhpc_slurmdb_upgrade

- name: Backup Slurm database
  ansible.builtin.shell:
    cmd: "{{ openhpc_slurm_accounting_storage_backup_cmd }}"
  delegate_to: "{{ openhpc_slurm_accounting_storage_backup_host }}"
  become: "{{ openhpc_slurm_accounting_storage_backup_become }}"
  run_once: true
  when: _openhpc_slurmdb_upgrade

- name: Ensure Slurm database service started
  ansible.builtin.systemd:
    name: mysql
    state: started
  when: _openhpc_slurmdb_state.changed | default(false)

- name: Run slurmdbd in foreground for upgrade
  ansible.builtin.expect:
    command: /usr/sbin/slurmdbd -D -vvv
    responses:
      (?i)Everything rolled up:
  # See https://wiki.fysik.dtu.dk/Niflheim_system/Slurm_installation/#upgrade-slurmdbd
  # and
  # https://github.com/SchedMD/slurm/blob/0ce058c5adcf63001ec2ad211c65e67b0e7682a8/src/plugins/accounting_storage/mysql/as_mysql_usage.c#L1042
  become_user: slurm
  when: _openhpc_slurmdb_upgrade
