- name: Check openhpc_slurm_control_host and openhpc_cluster_name
  assert:
    that:
      - openhpc_slurm_control_host is defined
      - openhpc_slurm_control_host != ''
      - openhpc_cluster_name is defined
      - openhpc_cluster_name != ''
    fail_msg: openhpc role variables not correctly defined, see detail above
  delegate_to: localhost
  run_once: true

- name: Check no host appears in more than one nodegroup
  assert:
    that: "{{ _openhpc_check_hosts.values() | select('greaterthan', 1) | length == 0 }}"
    fail_msg: |
      Some hosts appear more than once in inventory groups {{ _openhpc_node_inventory_groups | join(', ') }}:
      {{ _openhpc_check_hosts | dict2items | rejectattr('value', 'equalto', 1) | items2dict | to_nice_yaml }}
  vars:
    _openhpc_node_inventory_groups: "{{ openhpc_nodegroups | map(attribute='name') | map('regex_replace', '^', openhpc_cluster_name ~ '_') }}"
    _openhpc_check_hosts: "{{ groups | dict2items | list | selectattr('key', 'in', _openhpc_node_inventory_groups) | map(attribute='value') | flatten | community.general.counter }}"
  delegate_to: localhost
  run_once: true


# - name: Validate openhpc_nodegroups contain name
#   ansible.builtin.assert:
#     that:
#       - "'name' in nodegroup
#       - openhpc_cluster_name ~ '_' ~ nodegroup.name in group_names
#     fail_msg: "nodegroup does not specify a name or openhpc_cluster_name ~ '_' ~ nodegroup.name not found in inventory"

#   loop: "{{ openhpc_nodegroups }}"

- name: debug openhpc_nodegroups
  ansible.builtin.debug:
    msg: "{{ (item.gres | select('contains', 'file')) }} == {{ (item.gres | length) }}"
  loop: "{{ openhpc_nodegroups }}"
  when:
    - item.gres_autodetect | default(openhpc_gres_autodetect) == 'off'
    - "'gres' in item"
  delegate_to: localhost
  run_once: true

- name: Validate openhpc_nodegroups
  ansible.builtin.assert:
    that: "(item.gres | select('contains', 'file') | length) == (item.gres | length)"
    fail_msg: "GRES configuration(s) in openhpc_nodegroup '{{ item.name }}' do not include 'file' but GRES autodetection is not enabled"
  loop: "{{ openhpc_nodegroups }}"
  when:
    - item.gres_autodetect | default(openhpc_gres_autodetect) == 'off'
    - "'gres' in item"
  delegate_to: localhost
  run_once: true

- name: Fail if partition configuration is outdated
  assert:
    that: openhpc_slurm_partitions is not defined
    fail_msg: stackhpc.openhpc parameter openhpc_slurm_partitions has been replaced - see openhpc_nodegroups and openhpc_partitions
  delegate_to: localhost
  run_once: true

- name: Fail if munge key configuration is outdated
  assert:
    that: openhpc_munge_key is not defined
    fail_msg: stackhpc.openhpc parameter openhpc_munge_key has been replaced with openhpc_munge_key_b64
  delegate_to: localhost
  run_once: true
