- name: Check openhpc_slurm_control_host and openhpc_cluster_name
  assert:
    that:
      - openhpc_slurm_control_host is defined
      - openhpc_slurm_control_host != ''
      - openhpc_cluster_name is defined
      - openhpc_cluster_name != ''
    fail_msg: openhpc role variables not correctly defined, see detail above
  delegate_to: localhost
  run_once: true

- name: Check no host appears in more than one nodegroup
  assert:
    that: "{{ _openhpc_check_hosts.values() | select('greaterthan', 1) | length == 0 }}"
    fail_msg: |
      Some hosts appear more than once in inventory groups {{ _openhpc_node_inventory_groups | join(', ') }}:
      {{ _openhpc_check_hosts | dict2items | rejectattr('value', 'equalto', 1) | items2dict | to_nice_yaml }}
  vars:
    _openhpc_node_inventory_groups: "{{ openhpc_nodegroups | map(attribute='name') | map('regex_replace', '^', openhpc_cluster_name ~ '_') }}"
    _openhpc_check_hosts: "{{ groups | dict2items | list | selectattr('key', 'in', _openhpc_node_inventory_groups) | map(attribute='value') | flatten | community.general.counter }}"
  delegate_to: localhost
  run_once: true

- name: Check gres configuration when gres_autodetect is set
  assert:
    that:
      - _failure_reasons | selectattr('when', 'truthy') | length == 0
    fail_msg: >
      Your nodegroup definition must include a single gres dictionary containing a conf key
      if gres_autodetect is set. The following nodegroup failed this check: {{ item }}.
      Reasons for failure: {{ _failure_reasons | selectattr('when', 'truthy') | map(attribute='msg') | join(', ') }}
  vars:
    _openhpc_gres_autodetect_groups: "{{ openhpc_nodegroups | selectattr('gres_autodetect', 'defined') | selectattr('gres_autodetect', 'search', '(?!off).*') }}"
    _failure_reasons:
      - msg: The gres key was a list with more than one item
        when: "{{ item.gres | length != 1 }}"
      - msg: The gres dictionary does not contain a conf key
        when: "{{ item.gres.0.conf is not defined }}"
  delegate_to: localhost
  loop: "{{ _openhpc_gres_autodetect_groups }}"
  run_once: true

- name: Fail if partition configuration is outdated
  assert:
    that: openhpc_slurm_partitions is not defined
    fail_msg: stackhpc.openhpc parameter openhpc_slurm_partitions has been replaced - see openhpc_nodegroups and openhpc_partitions
  delegate_to: localhost
  run_once: true

- name: Fail if munge key configuration is outdated
  assert:
    that: openhpc_munge_key is not defined
    fail_msg: stackhpc.openhpc parameter openhpc_munge_key has been replaced with openhpc_munge_key_b64
  delegate_to: localhost
  run_once: true
