- name: Check openhpc_slurm_control_host and openhpc_cluster_name
  assert:
    that:
      - openhpc_slurm_control_host is defined
      - openhpc_slurm_control_host != ''
      - openhpc_cluster_name is defined
      - openhpc_cluster_name != ''
    fail_msg: openhpc role variables not correctly defined, see detail above
  delegate_to: localhost
  run_once: true

- name: Validate nodegroups define names
  # Needed for the next check..
  # NB: Don't validate names against inventory groups as those are allowed to be missing
  ansible.builtin.assert:
    that: "'name' in item"
    fail_msg: "A mapping in openhpc_nodegroups is missing 'name'"
  loop: "{{ openhpc_nodegroups }}"
  delegate_to: localhost
  run_once: true
  
- name: Check no host appears in more than one nodegroup
  assert:
    that: "{{ _openhpc_check_hosts.values() | select('greaterthan', 1) | length == 0 }}"
    fail_msg: |
      Some hosts appear more than once in inventory groups {{ _openhpc_node_inventory_groups | join(', ') }}:
      {{ _openhpc_check_hosts | dict2items | rejectattr('value', 'equalto', 1) | items2dict | to_nice_yaml }}
  vars:
    _openhpc_node_inventory_groups: "{{ openhpc_nodegroups | map(attribute='name') | map('regex_replace', '^', openhpc_cluster_name ~ '_') }}"
    _openhpc_check_hosts: "{{ groups | dict2items | list | selectattr('key', 'in', _openhpc_node_inventory_groups) | map(attribute='value') | flatten | community.general.counter }}"
  delegate_to: localhost
  run_once: true

- name: Validate GRES definitions
  ansible.builtin.assert:
    that: "(item.gres | select('contains', 'file') | length) == (item.gres | length)"
    fail_msg: "GRES configuration(s) in openhpc_nodegroups '{{ item.name }}' do not include 'file' but GRES autodetection is not enabled"
  loop: "{{ openhpc_nodegroups }}"
  when:
    - item.gres_autodetect | default(openhpc_gres_autodetect) == 'off'
    - "'gres' in item"
  delegate_to: localhost
  run_once: true

- name: Fail if partition configuration is outdated
  assert:
    that: openhpc_slurm_partitions is not defined
    fail_msg: stackhpc.openhpc parameter openhpc_slurm_partitions has been replaced - see openhpc_nodegroups and openhpc_partitions
  delegate_to: localhost
  run_once: true

- name: Fail if munge key configuration is outdated
  assert:
    that: openhpc_munge_key is not defined
    fail_msg: stackhpc.openhpc parameter openhpc_munge_key has been replaced with openhpc_munge_key_b64
  delegate_to: localhost
  run_once: true
