- name: Check openhpc_slurm_control_host and openhpc_cluster_name
  assert:
    that:
      - openhpc_slurm_control_host is defined
      - openhpc_slurm_control_host != ''
      - openhpc_cluster_name is defined
      - openhpc_cluster_name != ''
    fail_msg: openhpc role variables not correctly defined, see detail above
  delegate_to: localhost
  run_once: true

- name: Debug openhpc_merged_config on all hosts
  ansible.builtin.debug:
    var: openhpc_merged_config
  when: openhpc_debug_config | bool

- name: Validate merged configuration exists
  # Otherwise undefined variables used to define this willcause the SlurmdSpoolDir check below to incorrectly pass
  ansible.builtin.assert:
    that: openhpc_merged_config is defined
    fail_msg: "openhpc_merged_config is not defined. Run again setting -vv and -e openhpc_debug_config=true for debugging"

- name: Validate nodegroups define names
  # Needed for the next check..
  # NB: Don't validate names against inventory groups as those are allowed to be missing
  ansible.builtin.assert:
    that: "'name' in item"
    fail_msg: "A mapping in openhpc_nodegroups is missing 'name'"
  loop: "{{ openhpc_nodegroups }}"
  delegate_to: localhost
  run_once: true
  
- name: Check no host appears in more than one nodegroup
  assert:
    that: "{{ _openhpc_check_hosts.values() | select('greaterthan', 1) | length == 0 }}"
    fail_msg: |
      Some hosts appear more than once in inventory groups {{ _openhpc_node_inventory_groups | join(', ') }}:
      {{ _openhpc_check_hosts | dict2items | rejectattr('value', 'equalto', 1) | items2dict | to_nice_yaml }}
  vars:
    _openhpc_node_inventory_groups: "{{ openhpc_nodegroups | map(attribute='name') | map('regex_replace', '^', openhpc_cluster_name ~ '_') }}"
    _openhpc_check_hosts: "{{ groups | dict2items | list | selectattr('key', 'in', _openhpc_node_inventory_groups) | map(attribute='value') | flatten | community.general.counter }}"
  delegate_to: localhost
  run_once: true

- name: Validate GRES definitions
  ansible.builtin.assert:
    that: "(item.gres | select('contains', 'file') | length) == (item.gres | length)"
    fail_msg: "GRES configuration(s) in openhpc_nodegroups '{{ item.name }}' do not include 'file' but GRES autodetection is not enabled"
  loop: "{{ openhpc_nodegroups }}"
  when:
    - item.gres_autodetect | default(openhpc_gres_autodetect) == 'off'
    - "'gres' in item"
  delegate_to: localhost
  run_once: true

- name: Fail if partition configuration is outdated
  assert:
    that: openhpc_slurm_partitions is not defined
    fail_msg: stackhpc.openhpc parameter openhpc_slurm_partitions has been replaced - see openhpc_nodegroups and openhpc_partitions
  delegate_to: localhost
  run_once: true

- name: Fail if munge key configuration is outdated
  assert:
    that: openhpc_munge_key is not defined
    fail_msg: stackhpc.openhpc parameter openhpc_munge_key has been replaced with openhpc_munge_key_b64
  delegate_to: localhost
  run_once: true

- name: Fail if slurmd spool directory has changed
  # This will kill running jobs, so is usually incorrect
  # Check here relies on configless mode (always the case)
  # which caches config inside SlurmdSpoolDir on slurmd nodes:
  # https://slurm.schedmd.com/configless_slurm.html
  vars:
    # If "new" SlurmdSpoolDir not defined, assume slurm default:
    _openhpc_slurmd_spool_dir: "{{ openhpc_merged_config.SlurmdSpoolDir | default('/var/spool/slurmd') }}"
    _openhpc_force_slurmdspooldir_change_bool: "{{ openhpc_force_slurmdspooldir_change | bool }}"
  when: openhpc_enable.batch | default(false)
  block:
    - name: Find slurmd configuration cache
      ansible.builtin.find:
        paths:
          - /var/spool # this is an assumption!
        recurse: true
        contains: SlurmctldHost
      register: _openhpc_slurmd_conf_cache
    - name: Set fact for current SlurmdSpoolDir
      # If there is none, i.e. slurmd never started, don't care so assume same as new:
      ansible.builtin.set_fact:
        _openhpc_slurmd_spooldir_current: "{{ _openhpc_slurmd_conf_cache.files[0].path | dirname | dirname if _openhpc_slurmd_conf_cache.matched > 0 else _openhpc_slurmd_spool_dir }}"
    - name: Fail if SlurmdSpoolDir changing
      ansible.builtin.assert:
        that: _openhpc_slurmd_spooldir_current == _openhpc_slurmd_spool_dir
        fail_msg: >
          {% if _openhpc_force_slurmdspooldir_change_bool %}WARNING:{% else %}ERROR{% endif %} SlurmdSpoolDir is currently {{ _openhpc_slurmd_spooldir_current }}
          but new config will use {{ _openhpc_slurmd_spool_dir }} - this change will terminate any running jobs!
          {% if not _openhpc_force_slurmdspooldir_change_bool %}Set openhpc_force_slurmdspooldir_change to true to force this change.{% endif %}
      register: _openhpc_slurmd_spooldir_assert
      failed_when:
        - _openhpc_slurmd_spooldir_assert is failed
        - not _openhpc_force_slurmdspooldir_change_bool
