---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-openhpc"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        openhpc_enable:
          control: "{{ inventory_hostname in groups['testohpc_login'] }}"
          batch: "{{ inventory_hostname in groups['testohpc_compute'] }}"
          runtime: true
        openhpc_slurm_control_host: "{{ groups['testohpc_login'] | first }}"
        openhpc_slurm_partitions:
          - name: "compute"
        openhpc_cluster_name: testohpc
        openhpc_slurm_configless: true
        openhpc_slurm_job_comp_type: jobcomp/filetxt
