---
- name: Converge
  hosts: all
  vars:
    openhpc_enable:
      control: "{{ inventory_hostname in groups['testohpc_control'] }}"
      batch: "{{ inventory_hostname in groups['testohpc_compute'] }}"
      runtime: true
    openhpc_slurm_control_host: "{{ groups['testohpc_control'] | first }}"
    openhpc_slurm_partitions:
      - name: "compute"
    openhpc_cluster_name: testohpc
    openhpc_slurm_configless: true
    openhpc_login_only_nodes: 'testohpc_login'
  tasks:
    - name: "Include ansible-role-openhpc"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
