---
driver:
  name: podman
platforms:
  - name: testohpc-control
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_control
    command: "/bin/bash -c 'dnf -y install systemd && /sbin/init'" # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
      
  - name: testohpc-login-0
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_login
    command: "/bin/bash -c 'dnf -y install systemd && /sbin/init'" # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1

  - name: testohpc-login-1
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_login
    command: "/bin/bash -c 'dnf -y install systemd && /sbin/init'" # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
  
  - name: testohpc-compute-0
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
    command: "/bin/bash -c 'dnf -y install systemd && /sbin/init'" # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
  - name: testohpc-compute-1
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
    command: "/bin/bash -c 'dnf -y install systemd && /sbin/init'" # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
provisioner:
  name: ansible
  # ansible_args:
  #   - --limit=testohpc-control,testohpc-compute-0
verifier:
  name: ansible
