---
driver:
  name: podman
platforms:
  - name: testohpc-login-0
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_login
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
provisioner:
  name: ansible
  inventory:
    hosts:
      testohpc_compute: {}

verifier:
  name: ansible
