---
driver:
  name: podman
platforms:
  - name: testohpc-login-0
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_login
    command: 'dnf -y install systemd && /sbin/init' # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
  - name: compute-a
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
    command: 'dnf -y install systemd && /sbin/init' # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
  - name: compute10
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
    command: 'dnf -y install systemd && /sbin/init' # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
provisioner:
  name: ansible
verifier:
  name: ansible
