---
driver:
  name: podman
platforms:
  - name: testohpc-login-0
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_login
    command: "/bin/bash -c 'dnf -y install systemd && /sbin/init'" # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
  - name: testohpc-part1-0
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
      - testohpc_part1
    command: "/bin/bash -c 'dnf -y install systemd && /sbin/init'" # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
  - name: testohpc-part1-1
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
      - testohpc_part1
    command: "/bin/bash -c 'dnf -y install systemd && /sbin/init'" # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
  - name: testohpc-part2-0
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
      - testohpc_part2
    command: "/bin/bash -c 'dnf -y install systemd && /sbin/init'" # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
  - name: testohpc-part2-1
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
      - testohpc_part2
    command: "/bin/bash -c 'dnf -y install systemd && /sbin/init'" # not in RL9 image
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: net1
provisioner:
  name: ansible
verifier:
  name: ansible
