---
name: 2x partitions, group is partition
driver:
  name: docker
platforms:
  - name: testohpc-login-0
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_login
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: net1
  - name: testohpc-grp1-0
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
      - testohpc_grp1
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: net1
  - name: testohpc-grp1-1
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
      - testohpc_grp1
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: net1
  - name: testohpc-grp2-0
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
      - testohpc_grp2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: net1
  - name: testohpc-grp2-1
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_compute
      - testohpc_grp2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: net1
provisioner:
  name: ansible
verifier:
  name: ansible
