---
- name: Converge
  hosts: all
  vars:
    openhpc_enable:
      control: "{{ inventory_hostname in groups['testohpc_login'] }}"
      batch: "{{ inventory_hostname in groups['testohpc_compute'] }}"
      database: "{{ inventory_hostname in groups['testohpc_login'] }}"
      runtime: true
    openhpc_slurm_accounting_storage_type: 'accounting_storage/slurmdbd'
    openhpc_slurmdbd_mysql_database: slurm_acct_db
    openhpc_slurmdbd_mysql_password: secure-password
    openhpc_slurmdbd_mysql_username: slurm
    openhpc_slurm_control_host: "{{ groups['testohpc_login'] | first }}"
    openhpc_slurm_partitions:
      - name: "compute"
    openhpc_cluster_name: testohpc
  tasks:
    - name: "Include ansible-role-openhpc"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
