---

- name: Verify slurmrestd is working properly
  hosts: testohpc_login
  tasks:
  - name: Get slurm token
    shell: scontrol token | sed s,SLURM_JWT=,,
    register: _root_jwt_token
  - name: Query slurmrestd (slurmdbd)
    register: _slurmrestd_ping_response
    ansible.builtin.uri:
      headers:
        "X-SLURM-USER-TOKEN": "{{ _root_jwt_token.stdout }}"
      url: http://127.0.0.1:6282/slurmdb/v0.0.42/ping
      return_content: true
  - debug:
      var: _slurmrestd_ping_response
  - name: Check slurmrestd ping response
    ansible.builtin.assert:
      that:
        - _slurmrestd_ping_response.status == 200
        - _slurmrestd_ping_response.json.pings[0].responding

- name: Check slurm hostlist
  hosts: testohpc_login
  tasks:
  - name: Submit a test job
    command: sbatch --wrap hostname --parsable
    register: job

  - name: Allow some time for the job to complete
    pause:
      seconds: 10

  - name: Query sacct for job that was submitted
    command: sacct -j {{ job.stdout }} -p
    register: sacct

  - name: Check that job is in database
    vars:
      record: "{{ sacct.stdout_lines[1].split('|') }}"
    assert:
      # Expected: JobID|JobName|Partition|Account|AllocCPUS|State|ExitCode|
      that:
        - record[0] == job.stdout
        - record[5] == "COMPLETED"
      fail_msg: "FAILED - actual value: {{ sacct.stdout_lines[1] }}"
